from Sprint2.campaigns import campaignspage
from data.data import email_Campaña
from data.data import password_campaña
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

#Haria falta el ingresar a la cuenta

def test_panel_actions(driver):
    campaigns = campaignspage(driver)
    campaigns.navigate_home()
    #Ingreso
    campaigns.select_button_email() 
    campaigns.select_text_email()
    campaigns.text_email(email_Campaña) 
    campaigns.select_text_password()
    campaigns.text_password(password_campaña)
    time.sleep(5)
    campaigns.select_checkbox()  # Resolver CAPTCHA manualmente  buscar como no hacerlo manual
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable(campaigns.BUTTON_LOGIN))
    campaigns.select_button_login()
    #seleccionar campañas
    campaigns.select_CAMPAIGNS_AND_MARKET()
    campaigns.select_CAMPAIGNS()
    #Selccion de filtros 
    campaigns.select_FILTER_DROPDOWN()
    campaigns.select_FILTER_HIGHEST_INCOME()
    time.sleep(20)
    campaigns.select_FILTER_DROPDOWN()
    campaigns.select_FILTER_LOWEST_INCOME()
    time.sleep(20)
    campaigns.select_FILTER_DROPDOWN()
    campaigns.select_FILTER_HIGHEST_DEPOSIT()
    time.sleep(20)
    campaigns.select_FILTER_DROPDOWN()
    campaigns.select_FILTER_LOWEST_DEPOSIT()
    time.sleep(20)
    campaigns.select_FILTER_CLEAR()
    campaigns.select_FILTER_CPA()
    time.sleep(20)
    campaigns.select_FILTER_CLEAR()
    campaigns.select_FILTER_RS()
    time.sleep(20)
    campaigns.select_FILTER_CLEAR()
    campaigns.select_FILTER_TEXTAREA_MANUAL_click()
    time.sleep(5)
    campaigns.select_FILTER_TEXTAREA_MANUAL("México")
    time.sleep(10)
    campaigns.select_FILTER_TEXTAREA_SELECT()
    time.sleep(10)
    campaigns.select_FILTER_TEXTAREA_X()
    time.sleep(5)
    campaigns.select_FILTER_TEXTAREA_MANUAL_click()
    campaigns.select_FILTER_PLACEHOLDER_STATUS()
    time.sleep(20)
    campaigns.select_FILTER_TEXTAREA_X()
    campaigns.select_FILTER_TEXTAREA_MANUAL_click()
    campaigns.select_FILTER_PLACEHOLDER_COUNTRIES()
    time.sleep(20)
    campaigns.select_FILTER_TEXTAREA_X()
    campaigns.select_FILTER_TEXTAREA_MANUAL_click()
    campaigns.select_FILTER_PLACEHOLDER_OPERATOR()
    time.sleep(20)
    campaigns.select_FILTER_TEXTAREA_X()
    campaigns.select_FILTER_CHIPS()
    campaigns.select_FILTER_CHIPS_ACTIVE()
    campaigns.select_FILTER_CHIPS_X()
    campaigns.select_FILTER_CHIPS_CLOSED()
    campaigns.select_FILTER_CHIPS_X()
    campaigns.select_FILTER_CHIPS_SUSPENDED()
    campaigns.select_FILTER_CHIPS_X()
    campaigns.select_FILTER_CHIPS_ARGENTINA()
    campaigns.select_FILTER_CHIPS_X()
    campaigns.select_FILTER_CHIPS_888SPORT()
    campaigns.select_FILTER_CHIPS_X()
    time.sleep(20)
    campaigns.select_FILTER_CHIPS_ACTIVE()
    campaigns.select_FILTER_CHIPS_STATUS()
    campaigns.select_FILTER_CHIPS_ARGENTINA()
    campaigns.select_FILTER_CHIPS_MORE_COUNTRIES()
    campaigns.select_FILTER_CHIPS_SPAIN()
    campaigns.select_FILTER_CHIPS_FEWER_COUNTRIES()
    campaigns.select_FILTER_CHIPS_COUNTRIES()
    campaigns.select_FILTER_CHIPS_888SPORT()
    campaigns.select_FILTER_CHIPS_MORE_OPERATORS()
    campaigns.select_FILTER_CHIPS_1WIN()
    campaigns.select_FILTER_CHIPS_FEWER_OPERATORS()
    campaigns.select_FILTER_CHIPS_OPERATOR()
    campaigns.select_FILTER_CHIPS_APPLY()
    campaigns.select_FILTER_CLEAR()

    #seleccionar link 
    campaigns.select_SEE_DETAILS()
    campaigns.select_PROMOTE_CAMPAIGNS_LINK1()
    campaigns.select_CHECK_TYC_LINK()
    campaigns.select_BUTTON_CREATE_LINK()
    campaigns.select_COPY_LINK()
    time.sleep(5)
    campaigns.select_BUTTON_FINISH()
    campaigns.select_REQUEST_LINK2_DESDE_ELMAS()
    campaigns.select_BUTTON_CLOSE()
    campaigns.select_BUTTON_COPY_LINK()
    campaigns.select_BUTTON_FINAL()
    
