from Commizzion.campaign_management import managementpage
from data.data import email_Campaña
from data.data import password_campaña
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

#Haria falta el ingresar a la cuenta

def test_management(driver):
    managemen = managementpage(driver)
    managemen.navigate_home()
    #Ingreso
    managemen.select_button_email() 
    managemen.select_text_email()
    managemen.text_email(email_Campaña) 
    managemen.select_text_password()
    managemen.text_password(password_campaña)
    time.sleep(5)
    managemen.select_checkbox()  
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable(managemen.BUTTON_LOGIN))
    managemen.select_button_login()
    #seleccionar campañas
    managemen.select_CAMPAIGNS_AND_MARKET()
    managemen.select_MANAGEMENT()
    #Selccion de filtros 
    managemen.select_FILTER_DROPDOWN()
    managemen.select_FILTER_HIGHEST_INCOME()
    time.sleep(10)
    managemen.select_FILTER_DROPDOWN()
    managemen.select_FILTER_LOWEST_INCOME()
    time.sleep(10)
    managemen.select_FILTER_DROPDOWN()
    managemen.select_FILTER_HIGHEST_DEPOSIT()
    time.sleep(10)
    managemen.select_FILTER_DROPDOWN()
    managemen.select_FILTER_LOWEST_DEPOSIT()
    time.sleep(10)
    managemen.select_FILTER_CLEAR()
    managemen.select_FILTER_CPA()
    time.sleep(10)
    managemen.select_FILTER_CLEAR()
    managemen.select_FILTER_RS()
    time.sleep(10)
    managemen.select_FILTER_CLEAR()
    managemen.select_FILTER_TEXTAREA_MANUAL_click()
    time.sleep(5)
    managemen.select_FILTER_TEXTAREA_MANUAL("México")
    time.sleep(10)
    managemen.select_FILTER_TEXTAREA_SELECT()
    time.sleep(10)
    managemen.select_FILTER_TEXTAREA_X()
    time.sleep(5)
    managemen.select_FILTER_TEXTAREA_MANUAL_click()
    managemen.select_FILTER_PLACEHOLDER_STATUS()
    time.sleep(10)
    managemen.select_FILTER_TEXTAREA_X()
    managemen.select_FILTER_TEXTAREA_MANUAL_click()
    managemen.select_FILTER_PLACEHOLDER_COUNTRIES()
    time.sleep(10)
    managemen.select_FILTER_TEXTAREA_X()
    managemen.select_FILTER_TEXTAREA_MANUAL_click()
    managemen.select_FILTER_PLACEHOLDER_OPERATOR()
    time.sleep(10)
    managemen.select_FILTER_TEXTAREA_X()
    managemen.select_FILTER_CHIPS()
    managemen.select_FILTER_CHIPS_ACTIVE()
    managemen.select_FILTER_CHIPS_X()
    managemen.select_FILTER_CHIPS_CLOSED()
    managemen.select_FILTER_CHIPS_X()
    managemen.select_FILTER_CHIPS_SUSPENDED()
    managemen.select_FILTER_CHIPS_X()
    managemen.select_FILTER_CHIPS_ARGENTINA()
    managemen.select_FILTER_CHIPS_X()
    managemen.select_FILTER_CHIPS_888SPORT()
    managemen.select_FILTER_CHIPS_X()
    time.sleep(10)
    managemen.select_FILTER_CHIPS_ACTIVE()
    managemen.select_FILTER_CHIPS_STATUS()
    managemen.select_FILTER_CHIPS_ARGENTINA()
    managemen.select_FILTER_CHIPS_MORE_COUNTRIES()
    managemen.select_FILTER_CHIPS_SPAIN()
    managemen.select_FILTER_CHIPS_FEWER_COUNTRIES()
    managemen.select_FILTER_CHIPS_COUNTRIES()
    managemen.select_FILTER_CHIPS_888SPORT()
    managemen.select_FILTER_CHIPS_MORE_OPERATORS()
    managemen.select_FILTER_CHIPS_1WIN()
    managemen.select_FILTER_CHIPS_FEWER_OPERATORS()
    managemen.select_FILTER_CHIPS_OPERATOR()
    managemen.select_FILTER_CHIPS_APPLY()
    managemen.select_FILTER_CLEAR()

    #seleccionar link 
    managemen.select_SEE_DETAILS()
    managemen.select_PROMOTE_CAMPAIGNS_LINK1()
    managemen.select_CHECK_TYC_LINK()
    managemen.select_BUTTON_CREATE_LINK()
    managemen.select_COPY_LINK()
    time.sleep(5)
    managemen.select_BUTTON_FINISH()
    managemen.select_REQUEST_LINK2_DESDE_ELMAS()
    managemen.select_BUTTON_CLOSE()
    managemen.select_BUTTON_COPY_LINK()
    managemen.select_BUTTON_FINAL()