from Commizzion.campaigns import campaignspage
from data.data import email_Campaña
from data.data import password_campaña
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time

#Haria falta el ingresar a la cuenta

def test_campaigns(driver):
    campaigns = campaignspage(driver)
    campaigns.navigate_home()
    #Ingreso
    campaigns.select_button_email() 
    campaigns.select_text_email()
    campaigns.text_email(email_Campaña) 
    campaigns.select_text_password()
    campaigns.text_password(password_campaña)
    time.sleep(5)
    campaigns.select_checkbox()  
    WebDriverWait(driver, 20).until(EC.element_to_be_clickable(campaigns.BUTTON_LOGIN))
    campaigns.select_button_login()
    #seleccionar campañas
    campaigns.select_campaigns_and_market() 
    campaigns.select_campaigns() 
    #selccion de filtros  
    campaigns.select_filter_dropdown() 
    campaigns.select_filter_highest_income() 
    time.sleep(10) 
    campaigns.select_filter_dropdown() 
    campaigns.select_filter_lowest_income() 
    time.sleep(10) 
    campaigns.select_filter_dropdown() 
    campaigns.select_filter_highest_deposit() 
    time.sleep(10) 
    campaigns.select_filter_dropdown() 
    campaigns.select_filter_lowest_deposit() 
    time.sleep(10) 
    campaigns.select_filter_clear() 
    campaigns.select_filter_cpa() 
    time.sleep(10) 
    campaigns.select_filter_clear() 
    campaigns.select_filter_rs() 
    time.sleep(10) 
    campaigns.select_filter_clear() 
    campaigns.select_filter_textarea_manual_click() 
    time.sleep(5) 
    campaigns.select_filter_textarea_manual("México") 
    time.sleep(10) 
    campaigns.select_filter_textarea_select() 
    time.sleep(10) 
    campaigns.select_filter_textarea_x() 
    time.sleep(5) 
    campaigns.select_filter_textarea_manual_click() 
    campaigns.select_filter_placeholder_status() 
    time.sleep(10) 
    campaigns.select_filter_textarea_x() 
    campaigns.select_filter_textarea_manual_click() 
    campaigns.select_filter_placeholder_countries() 
    time.sleep(10) 
    campaigns.select_filter_textarea_x() 
    campaigns.select_filter_textarea_manual_click() 
    campaigns.select_filter_placeholder_operator() 
    time.sleep(10) 
    campaigns.select_filter_textarea_x() 
    campaigns.select_filter_chips() 
    campaigns.select_filter_chips_active() 
    campaigns.select_filter_chips_x() 
    campaigns.select_filter_chips_closed() 
    campaigns.select_filter_chips_x() 
    campaigns.select_filter_chips_suspended() 
    campaigns.select_filter_chips_x() 
    campaigns.select_filter_chips_argentina() 
    campaigns.select_filter_chips_x() 
    campaigns.select_filter_chips_888sport() 
    campaigns.select_filter_chips_x() 
    time.sleep(10) 
    campaigns.select_filter_chips_active() 
    campaigns.select_filter_chips_status() 
    campaigns.select_filter_chips_argentina() 
    campaigns.select_filter_chips_more_countries() 
    campaigns.select_filter_chips_spain() 
    campaigns.select_filter_chips_fewer_countries() 
    campaigns.select_filter_chips_countries() 
    campaigns.select_filter_chips_888sport() 
    campaigns.select_filter_chips_more_operators() 
    campaigns.select_filter_chips_1win() 
    campaigns.select_filter_chips_fewer_operators() 
    campaigns.select_filter_chips_operator() 
    campaigns.select_filter_chips_apply() 
    campaigns.select_filter_clear() 
    #seleccionar link  
    campaigns.select_see_details() 
    campaigns.select_promote_campaigns_link1() 
    campaigns.select_check_tyc_link() 
    campaigns.select_button_create_link() 
    campaigns.select_copy_link() 
    time.sleep(5) 
    campaigns.select_button_finish() 
    campaigns.select_request_link2_desde_elmas() 
    campaigns.select_button_close() 
    campaigns.select_button_copy_link() 
    campaigns.select_button_final() 
